import { printHtml, fmtMoney, fmtDate } from "@/lib/utils";
import type { Contact, FinDoc, Settings } from "@/lib/types";
import { computeDocTotals } from "./DocFormModal";

const TITLES: Record<string, string> = {
  invoice: "INVOICE",
  quotation: "QUOTATION",
  purchase: "PURCHASE ORDER",
};

export function printDoc(
  doc: FinDoc,
  settings: Settings,
  party?: Contact
) {
  const t = computeDocTotals(doc);
  const esc = (s: string) => s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string));
  const rows = doc.lines
    .map(
      (l, i) => `<tr>
        <td>${i + 1}</td>
        <td><b>${esc(l.name)}</b></td>
        <td class="right">${l.qty}</td>
        <td class="right">${fmtMoney(l.unitPrice, settings.currency)}</td>
        <td class="right">${fmtMoney(l.qty * l.unitPrice, settings.currency)}</td>
      </tr>`
    )
    .join("");

  const paid = doc.paidAmount ?? 0;
  const balance = Math.max(0, t.total - paid);

  printHtml(
    `${TITLES[doc.kind]} ${doc.number}`,
    `<div class="header-row">
      <div>
        <h1 style="color:#4f46e5">${esc(settings.orgName)}</h1>
        <p class="muted">${esc(settings.orgAddress ?? "")}${settings.orgPhone ? " · " + esc(settings.orgPhone) : ""}${settings.orgEmail ? " · " + esc(settings.orgEmail) : ""}</p>
      </div>
      <div style="text-align:right">
        <h1>${TITLES[doc.kind]}</h1>
        <p class="muted"><b>${esc(doc.number)}</b></p>
        <p class="muted">Date: ${fmtDate(doc.date)}${doc.dueDate ? ` · Due: ${fmtDate(doc.dueDate)}` : ""}</p>
      </div>
    </div>
    ${party ? `<p style="margin-top:10px"><span class="muted">Bill to:</span><br/><b>${esc(party.name)}</b>${party.address ? `<br/><span class="muted">${esc(party.address)}</span>` : ""}${party.phone ? `<br/><span class="muted">${esc(party.phone)}</span>` : ""}</p>` : ""}
    <table>
      <thead><tr><th>#</th><th>Description</th><th class="right">Qty</th><th class="right">Rate</th><th class="right">Amount</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <table class="totals" style="width:280px;margin-left:auto">
      <tr><td>Subtotal</td><td class="right">${fmtMoney(t.subtotal, settings.currency)}</td></tr>
      ${t.discount ? `<tr><td>Discount</td><td class="right">−${fmtMoney(t.discount, settings.currency)}</td></tr>` : ""}
      ${t.tax ? `<tr><td>Tax (${doc.taxRate ?? 0}%)</td><td class="right">${fmtMoney(t.tax, settings.currency)}</td></tr>` : ""}
      <tr style="font-weight:bold;font-size:15px"><td>Total</td><td class="right">${fmtMoney(t.total, settings.currency)}</td></tr>
      ${doc.kind === "invoice" && paid > 0 ? `<tr><td>Paid</td><td class="right" style="color:#059669">−${fmtMoney(Math.min(paid, t.total), settings.currency)}</td></tr><tr style="font-weight:bold"><td>Balance due</td><td class="right" style="color:${balance > 0 ? "#e11d48" : "#059669"}">${fmtMoney(balance, settings.currency)}</td></tr>` : ""}
    </table>
    ${doc.notes ? `<p class="muted" style="margin-top:18px">${esc(doc.notes)}</p>` : ""}
    <p class="muted" style="margin-top:26px;border-top:1px solid #e5e7eb;padding-top:10px">Generated by Stash · Thank you!</p>`
  );
}
